### ISSUE TITLE
Syntax Highlighting using ``` java fails

### ISSUE THREAD

**Issue by abbourne** [walle/gimli#33]
I've installed gimli 0.4.1 with coderay 1.0.8 and the syntax highlighting in markdown files is not working for me.

using the back tick notation

``` java
 --- java code here
```

in my markdown file, I always get the following error:

/Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay/helpers/plugin.rb:220:in `validate_id': Invalid id given: java         (ArgumentError)
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay/helpers/plugin.rb:50:in`[]'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay/encoder.rb:83:in `encode'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay.rb:198:in`encode'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay/tokens_proxy.rb:23:in `encode'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/coderay-1.0.8/lib/coderay/tokens_proxy.rb:32:in`method_missing'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/code_block.rb:21:in `highlighted'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/code.rb:33:in`block in process'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/code.rb:32:in `each'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/code.rb:32:in`process'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/renderer.rb:58:in `post_process_data'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/markup/renderer.rb:30:in`render'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/converter.rb:27:in `block in convert!'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/converter.rb:25:in`each'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli/converter.rb:25:in `convert!'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/lib/gimli.rb:29:in`process!'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/gems/gimli-0.4.1/bin/gimli:23:in `<top (required)>'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/bin/gimli:19:in`load'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/bin/gimli:19:in `<main>'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/bin/ruby_noexec_wrapper:14:in`eval'
    from /Users/billb/.rvm/gems/ruby-1.9.3-p327@octopress/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by cen1** [comment]
Still the same problem in version 0.5.9. Why was this closed?
